using IronPython.Hosting;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Scripting.Hosting;
using Microsoft.VisualStudio.Web.CodeGeneration.Templating;
using Microsoft.Scripting;
using System.Diagnostics;

namespace VirusTracker.Helpers
{
    public class PythonManager
    {
        private ProcessStartInfo start;
        private Process process;
        public PythonManager()
        {
            start = new ProcessStartInfo();
            start.FileName = @"D:\Python\python.exe";
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            start.LoadUserProfile = true;
        }
        public string PredictSentiment(string cmd, string args)
        {
            start.Arguments = string.Format("\"{0}\" \"{1}\"", cmd, args);
            process = Process.Start(start);
            StreamReader reader = process.StandardOutput;
                
            string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
            string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
            Debug.Write(stderr);
            return(result);
            
        }
        public void CloseProcess()
        {
            process.Kill();
        }
    }
}
